using FootballHub.Domain.Entities;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace FootballHub.Infrastructure.Persistence;

public class DatabaseInitializer : IHostedService 
{
    private readonly IServiceProvider _serviceProvider;
        
    public DatabaseInitializer(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }
    
    public Task StartAsync(CancellationToken cancellationToken)
    {
        using (var scope = _serviceProvider.CreateScope())
        {
            var dbContext = scope.ServiceProvider.GetRequiredService<MainDbContext>();

            var countries = dbContext.Countries.ToList();
            if (!countries.Any())
            {
                 countries = new List<Country>
                {
                    new() { Name = "Afganistan", ShortName = "AFG" },
                    new() { Name = "Albania", ShortName = "ALB" },
                    new() { Name = "Algieria", ShortName = "DZA" },
                    new() { Name = "Andora", ShortName = "AND" },
                    new() { Name = "Anglia", ShortName = "ENG" },
                    new() { Name = "Angola", ShortName = "AGO" },
                    new() { Name = "Antigua i Barbuda", ShortName = "ATG" },
                    new() { Name = "Arabia Saudyjska", ShortName = "SAU" },
                    new() { Name = "Argentyna", ShortName = "ARG" },
                    new() { Name = "Armenia", ShortName = "ARM" },
                    new() { Name = "Australia", ShortName = "AUS" },
                    new() { Name = "Austria", ShortName = "AUT" },
                    new() { Name = "Azerbejdżan", ShortName = "AZE" },
                    new() { Name = "Bahamy", ShortName = "BHS" },
                    new() { Name = "Bahrajn", ShortName = "BHR" },
                    new() { Name = "Bangladesz", ShortName = "BGD" },
                    new() { Name = "Barbados", ShortName = "BRB" },
                    new() { Name = "Belgia", ShortName = "BEL" },
                    new() { Name = "Belize", ShortName = "BLZ" },
                    new() { Name = "Benin", ShortName = "BEN" },
                    new() { Name = "Bhutan", ShortName = "BTN" },
                    new() { Name = "Białoruś", ShortName = "BLR" },
                    new() { Name = "Boliwia", ShortName = "BOL" },
                    new() { Name = "Bośnia i Hercegowina", ShortName = "BIH" },
                    new() { Name = "Botswana", ShortName = "BWA" },
                    new() { Name = "Brazylia", ShortName = "BRA" },
                    new() { Name = "Brunei", ShortName = "BRN" },
                    new() { Name = "Bułgaria", ShortName = "BGR" },
                    new() { Name = "Burkina Faso", ShortName = "BFA" },
                    new() { Name = "Burundi", ShortName = "BDI" },
                    new() { Name = "Chile", ShortName = "CHL" },
                    new() { Name = "Chiny", ShortName = "CHN" },
                    new() { Name = "Chorwacja", ShortName = "HRV" },
                    new() { Name = "Cypr", ShortName = "CYP" },
                    new() { Name = "Czarnogóra", ShortName = "MNE" },
                    new() { Name = "Czechy", ShortName = "CZE" },
                    new() { Name = "Dania", ShortName = "DNK" },
                    new() { Name = "Demokratyczna Republika Konga", ShortName = "COD" },
                    new() { Name = "Dominika", ShortName = "DMA" },
                    new() { Name = "Dominikana", ShortName = "DOM" },
                    new() { Name = "Dżibuti", ShortName = "DJI" },
                    new() { Name = "Egipt", ShortName = "EGY" },
                    new() { Name = "Ekwador", ShortName = "ECU" },
                    new() { Name = "Erytrea", ShortName = "ERI" },
                    new() { Name = "Estonia", ShortName = "EST" },
                    new() { Name = "Etiopia", ShortName = "ETH" },
                    new() { Name = "Fidżi", ShortName = "FJI" },
                    new() { Name = "Filipiny", ShortName = "PHL" },
                    new() { Name = "Finlandia", ShortName = "FIN" },
                    new() { Name = "Francja", ShortName = "FRA" },
                    new() { Name = "Gabon", ShortName = "GAB" },
                    new() { Name = "Gambia", ShortName = "GMB" },
                    new() { Name = "Ghana", ShortName = "GHA" },
                    new() { Name = "Grecja", ShortName = "GRC" },
                    new() { Name = "Grenada", ShortName = "GRD" },
                    new() { Name = "Gruzja", ShortName = "GEO" },
                    new() { Name = "Guatemala", ShortName = "GTM" },
                    new() { Name = "Gwinea", ShortName = "GIN" },
                    new() { Name = "Gwinea Bissau", ShortName = "GNB" },
                    new() { Name = "Gwinea Równikowa", ShortName = "GNQ" },
                    new() { Name = "Gujana", ShortName = "GUY" },
                    new() { Name = "Haiti", ShortName = "HTI" },
                    new() { Name = "Hiszpania", ShortName = "ESP" },
                    new() { Name = "Holandia", ShortName = "NLD" },
                    new() { Name = "Honduras", ShortName = "HND" },
                    new() { Name = "Indie", ShortName = "IND" },
                    new() { Name = "Indonezja", ShortName = "IDN" },
                    new() { Name = "Irak", ShortName = "IRQ" },
                    new() { Name = "Iran", ShortName = "IRN" },
                    new() { Name = "Irlandia", ShortName = "IRL" },
                    new() { Name = "Irlandia Północna", ShortName = "NIR" },
                    new() { Name = "Islandia", ShortName = "ISL" },
                    new() { Name = "Izrael", ShortName = "ISR" },
                    new() { Name = "Jamajka", ShortName = "JAM" },
                    new() { Name = "Japonia", ShortName = "JPN" },
                    new() { Name = "Jemen", ShortName = "YEM" },
                    new() { Name = "Jordania", ShortName = "JOR" },
                    new() { Name = "Kambodża", ShortName = "KHM" },
                    new() { Name = "Kamerun", ShortName = "CMR" },
                    new() { Name = "Kanada", ShortName = "CAN" },
                    new() { Name = "Katar", ShortName = "QAT" },
                    new() { Name = "Kazachstan", ShortName = "KAZ" },
                    new() { Name = "Kenia", ShortName = "KEN" },
                    new() { Name = "Kirgistan", ShortName = "KGZ" },
                    new() { Name = "Kiribati", ShortName = "KIR" },
                    new() { Name = "Kolumbia", ShortName = "COL" },
                    new() { Name = "Komory", ShortName = "COM" },
                    new() { Name = "Kongo", ShortName = "COG" },
                    new() { Name = "Korea Południowa", ShortName = "KOR" },
                    new() { Name = "Korea Północna", ShortName = "PRK" },
                    new() { Name = "Kostaryka", ShortName = "CRI" },
                    new() { Name = "Kuba", ShortName = "CUB" },
                    new() { Name = "Kuwejt", ShortName = "KWT" },
                    new() { Name = "Laos", ShortName = "LAO" },
                    new() { Name = "Lesotho", ShortName = "LSO" },
                    new() { Name = "Liban", ShortName = "LBN" },
                    new() { Name = "Liberia", ShortName = "LBR" },
                    new() { Name = "Libia", ShortName = "LBY" },
                    new() { Name = "Liechtenstein", ShortName = "LIE" },
                    new() { Name = "Litwa", ShortName = "LTU" },
                    new() { Name = "Luksemburg", ShortName = "LUX" },
                    new() { Name = "Łotwa", ShortName = "LVA" },
                    new() { Name = "Macedonia Północna", ShortName = "MKD" },
                    new() { Name = "Madagaskar", ShortName = "MDG" },
                    new() { Name = "Malawi", ShortName = "MWI" },
                    new() { Name = "Malediwy", ShortName = "MDV" },
                    new() { Name = "Malezja", ShortName = "MYS" },
                    new() { Name = "Mali", ShortName = "MLI" },
                    new() { Name = "Malta", ShortName = "MLT" },
                    new() { Name = "Maroko", ShortName = "MAR" },
                    new() { Name = "Mauretania", ShortName = "MRT" },
                    new() { Name = "Mauritius", ShortName = "MUS" },
                    new() { Name = "Meksyk", ShortName = "MEX" },
                    new() { Name = "Mikronezja", ShortName = "FSM" },
                    new() { Name = "Mołdawia", ShortName = "MDA" },
                    new() { Name = "Monako", ShortName = "MCO" },
                    new() { Name = "Mongolia", ShortName = "MNG" },
                    new() { Name = "Mozambik", ShortName = "MOZ" },
                    new() { Name = "Myanmar", ShortName = "MMR" },
                    new() { Name = "Namibia", ShortName = "NAM" },
                    new() { Name = "Nauru", ShortName = "NRU" },
                    new() { Name = "Nepal", ShortName = "NPL" },
                    new() { Name = "Niemcy", ShortName = "GER" },
                    new() { Name = "Niger", ShortName = "NER" },
                    new() { Name = "Nigeria", ShortName = "NGA" },
                    new() { Name = "Nikaragua", ShortName = "NIC" },
                    new() { Name = "Norwegia", ShortName = "NOR" },
                    new() { Name = "Nowa Zelandia", ShortName = "NZL" },
                    new() { Name = "Oman", ShortName = "OMN" },
                    new() { Name = "Pakistan", ShortName = "PAK" },
                    new() { Name = "Palau", ShortName = "PLW" },
                    new() { Name = "Panama", ShortName = "PAN" },
                    new() { Name = "Papua-Nowa Gwinea", ShortName = "PNG" },
                    new() { Name = "Paragwaj", ShortName = "PRY" },
                    new() { Name = "Peru", ShortName = "PER" },
                    new() { Name = "Polska", ShortName = "POL" },
                    new() { Name = "Portugalia", ShortName = "PRT" },
                    new() { Name = "Republika Środkowoafrykańska", ShortName = "CAF" },
                    new() { Name = "Republika Zielonego Przylądka", ShortName = "CPV" },
                    new() { Name = "Rosja", ShortName = "RUS" },
                    new() { Name = "Rumunia", ShortName = "ROU" },
                    new() { Name = "Rwanda", ShortName = "RWA" },
                    new() { Name = "Saint Kitts i Nevis", ShortName = "KNA" },
                    new() { Name = "Saint Lucia", ShortName = "LCA" },
                    new() { Name = "Saint Vincent i Grenadyny", ShortName = "VCT" },
                    new() { Name = "Salwador", ShortName = "SLV" },
                    new() { Name = "Samoa", ShortName = "WSM" },
                    new() { Name = "San Marino", ShortName = "SMR" },
                    new() { Name = "Senegal", ShortName = "SEN" },
                    new() { Name = "Serbia", ShortName = "SRB" },
                    new() { Name = "Seszele", ShortName = "SYC" },
                    new() { Name = "Sierra Leone", ShortName = "SLE" },
                    new() { Name = "Singapur", ShortName = "SGP" },
                    new() { Name = "Słowacja", ShortName = "SVK" },
                    new() { Name = "Słowenia", ShortName = "SVN" },
                    new() { Name = "Somalia", ShortName = "SOM" },
                    new() { Name = "Sri Lanka", ShortName = "LKA" },
                    new() { Name = "Stany Zjednoczone", ShortName = "USA" },
                    new() { Name = "Sudan", ShortName = "SDN" },
                    new() { Name = "Sudan Południowy", ShortName = "SSD" },
                    new() { Name = "Surinam", ShortName = "SUR" },
                    new() { Name = "Syria", ShortName = "SYR" },
                    new() { Name = "Szkocja", ShortName = "SCO" },
                    new() { Name = "Szwajcaria", ShortName = "CHE" },
                    new() { Name = "Szwecja", ShortName = "SWE" },
                    new() { Name = "Tadżykistan", ShortName = "TJK" },
                    new() { Name = "Tajlandia", ShortName = "THA" },
                    new() { Name = "Tanzania", ShortName = "TZA" },
                    new() { Name = "Timor Wschodni", ShortName = "TLS" },
                    new() { Name = "Togo", ShortName = "TGO" },
                    new() { Name = "Tonga", ShortName = "TON" },
                    new() { Name = "Trynidad i Tobago", ShortName = "TTO" },
                    new() { Name = "Tunezja", ShortName = "TUN" },
                    new() { Name = "Turcja", ShortName = "TUR" },
                    new() { Name = "Turkmenistan", ShortName = "TKM" },
                    new() { Name = "Tuvalu", ShortName = "TUV" },
                    new() { Name = "Uganda", ShortName = "UGA" },
                    new() { Name = "Ukraina", ShortName = "UKR" },
                    new() { Name = "Urugwaj", ShortName = "URY" },
                    new() { Name = "Uzbekistan", ShortName = "UZB" },
                    new() { Name = "Vanuatu", ShortName = "VUT" },
                    new() { Name = "Watykan", ShortName = "VAT" },
                    new() { Name = "Walia", ShortName = "WAL" },
                    new() { Name = "Wenezuela", ShortName = "VEN" },
                    new() { Name = "Węgry", ShortName = "HUN" },
                    new() { Name = "Wielka Brytania", ShortName = "GBR" },
                    new() { Name = "Wietnam", ShortName = "VNM" },
                    new() { Name = "Włochy", ShortName = "ITA" },
                    new() { Name = "Wybrzeże Kości Słoniowej", ShortName = "CIV" },
                    new() { Name = "Wyspy Marshalla", ShortName = "MHL" },
                    new() { Name = "Wyspy Salomona", ShortName = "SLB" },
                    new() { Name = "Wyspy Świętego Tomasza i Książęca", ShortName = "STP" },
                    new() { Name = "Zambia", ShortName = "ZMB" },
                    new() { Name = "Zimbabwe", ShortName = "ZWE" },
                    new() { Name = "Zjednoczone Emiraty Arabskie", ShortName = "ARE" },
                };
                dbContext.Countries.AddRange(countries);
                dbContext.SaveChanges();
            }
            return Task.CompletedTask;
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
